name: stationary_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  http: ^1.1.0
  pdf: ^3.10.8        # 👈 Lagu daray si PDF-ka loo abuuro
  printing: ^5.11.0   # 👈 Lagu daray si toos loogu print gareeyo oo loogu save gareeyo
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true